name:                magic-squares
github:              "diegofdz/magic-squares"
author:              "Diego Fernandez"

dependencies:
- base >= 4.7 && < 5
- array
- containers
- parallel

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  magic-squares-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    dependencies:
    - magic-squares

tests:
  magic-squares-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - magic-squares
